//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_DBEntities : DbContext
    {
        public Project_DBEntities()
            : base("name=Project_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Illness> Illnesses { get; set; }
        public virtual DbSet<MedicalAid> MedicalAids { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientRelative> PatientRelatives { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<Surbub> Surbubs { get; set; }
        public virtual DbSet<SysAdmin> SysAdmins { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
        public virtual DbSet<UAddress> UAddresses { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Vital> Vitals { get; set; }
    }
}
