//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Age { get; set; }
        public string ContactDetails { get; set; }
        public string ChipID { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> VitalID { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> IID { get; set; }
        public Nullable<int> AID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Illness Illness { get; set; }
        public virtual MedicalAid MedicalAid { get; set; }
        public virtual UAddress UAddress { get; set; }
        public virtual PatientRelative PatientRelative { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual Vital Vital { get; set; }
    }
}
