//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vital()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int VitalID { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<int> BloodPressure { get; set; }
        public Nullable<int> BloodSugar { get; set; }
        public Nullable<int> IronLevels { get; set; }
        public Nullable<int> WhiteBloodCells { get; set; }
        public Nullable<int> RedBloodCells { get; set; }
        public Nullable<int> Antibodies { get; set; }
        public Nullable<int> Glucose { get; set; }
        public Nullable<int> Cholesterol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
